BATCH_SIZE : 6 #how many renderings, change this to >1 to get OOM
TEXTURE_DROP_PROB: 50
OUTPUT_DIR : "output"
SEED : 62389572394075
### prompts
PROMPT : "A professional cartoon of nerdy bear, a masterpiece"
  
NEGATIVE_PROMPT : "" #longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality"
### geometry
MESH_RESOLUTION : 50  # resolution of the mesh to use (NxN vertices on square
W_RANGE : 0.95  # range of the weights used in Tutte. Closer to 1 makes more extreme deformation, 0 makes all weights uniform without ability to move
W_REGULARIZATION : 0.000  # weight on a term that makes each subtile the same area. If enabled, works well between 1^3 and 10^6
AREA_REGULARIZATION : 0.1  # weight on a term that penalizes too big weights in Tutte. There's no reason for very high weights, any deformation can be represented with smaller weights that sum to 1
RENDERER_IMAGE_DIM : 512 #working was 64
VISUALIZATION_FREQ : 200
TILING_RENDER_FREQ : 200
MODEL : "stabilityai/stable-diffusion-2-1-base"
GUIDANCE_SCALE : 100 #Parameter-free guidance parameter. High values (100) trade diversity for quality.
###optimization params
N_STEPS : 7000  # optimization steps
ONLY_TEXTURE_FROM_THIS_POINT: 7000
SCHEDULER : "step"  # "step" or "cosine" or "linear"
LR : 1e-1
LR_COLOR : 1e-2

TILING_TYPE: "ProjectivePlane" #Cylinder, KleinBottle, MobiusStrip, OrbifoldI, OrbifoldIHybrid, OrbifoldII,OrbifoldIIHybrid, OrbifoldIII, OrbifoldIV,OrbifoldIVHybrid, PinnedBoundary, ProjectivePlane, ReflectSquare, RightAngleHybrid, Torus, 
INPUT_OUTLINE: "/home/groueix/tiling/results.pkl" # This has to change
UV : "FIXED" # FIXED or SPATIAL, if SPATIAL uv(x,y) = x,y reset at every iteration
